import React from 'react';
import { Link } from 'react-router-dom';

const Hero = () => {
  return (
    <div className='hero'>
      <div className='hero1'>
        <h1 className='heroH1'>A R T E L</h1>
        <p className='heroP'>The premier community for sharing and discovering digital art generated by artificial intelligence! Our platform is dedicated to showcasing the incredible creative potential of AI-generated art.</p>
        <div className='heroBtns'>
            <Link to='/login' className='login bg-gradient-to-r from-blue-500 to-purple-500 rounded-md text-white'>Log In</Link>
            <Link to='/signup' className='signup bg-white border-2 border-gray-400 rounded-md'>Sign Up</Link>
        </div>
      </div>
      <div className='heroPost'>
        <div className='slideshow'>

        </div>
        <div className='heroPostBottom bg-gradient-to-r from-gray-50 to-stone-300'>
            <div className='iconContainer'>
            <img src="./assets/redHeart.png" alt="like" className="icon animate-pulse" />
            <img src="./assets/comments.png" alt="comment" className="icon" />
            </div>
            <p className='heroPostTag'>@ARTEL</p>
        </div>
      </div>
    </div>
  )
}

export default Hero
